# name: Build and Deploy
# on:
#   push:
#     branches:
#       - arun_work
# jobs:
#   build-and-deploy:
#     runs-on: windows-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14.x'
#       - name: Install dependencies
#         run: npm install
#       - name: Build app
#         run: npm run build
#       - name: Deploy to App Center
#         uses: microsoft/appcenter-action@v3
#         with:
#           app_secret: ${{ secrets.APP_CENTER_SECRET }}
#           app_name: 'sociable'
#           distribution_groups: 'Testers'
#           file: ${{ env.APK_FILE }}
#     env:
#       APK_FILE: '../.././android/app/build/outputs/apk/release/app-release.apk'
